export const SHOWCASE_COMPONENT_SEED_USER = {
  fullName: "Showcase Seeder",
  email: "showcase.seed@modular.local",
  role: "admin",
};

export const showcaseComponentsSeedData = [
  {
    id: "gradient-button",
    slug: "gradient-button",
    name: "Gradient Button",
    category: "buttons",
    description: "Animated gradient call-to-action button with hover scaling.",
    tags: ["button", "gradient", "animated"],
    difficulty: "beginner",
    author: "Showcase Team",
    demoAvailable: true,
    previewMetadata: { thumbnailKey: "gradient-button" },
    useCase: "Use for primary call-to-action actions in forms and hero sections.",
    accessibilityNotes: "Ensure visible focus ring and sufficient contrast for gradient text states.",
    responsiveNotes: "Button scales naturally on small screens when container width is constrained.",
    code: {
      jsx: "export default function GradientButton({ children = 'Deploy' }) { return <button className=\"gradient-button\">{children}</button>; }",
      css: ".gradient-button { border: none; border-radius: 10px; padding: 12px 32px; background: linear-gradient(90deg,#0d9488,#0891b2,#f97316); color: #fff; }",
    },
  },
  {
    id: "glass-card",
    slug: "glass-card",
    name: "Glass Card",
    category: "cards",
    description: "Glassmorphism card with configurable title, description, and elevation shadow.",
    tags: ["card", "glass", "glassmorphism"],
    difficulty: "beginner",
    author: "Showcase Team",
    demoAvailable: true,
    previewMetadata: { thumbnailKey: "glass-card" },
    useCase: "Use for dashboard cards and feature highlights with subtle depth.",
    accessibilityNotes: "Validate readable contrast for translucent backgrounds.",
    responsiveNotes: "Card width should collapse to container width on mobile.",
    code: {
      jsx: "export default function GlassCard({ title='Component Spotlight', description='Reusable card shell', elevated=false }) { return <article className={elevated ? 'glass-card glass-card--elevated' : 'glass-card'}><h3>{title}</h3><p>{description}</p></article>; }",
      css: ".glass-card { border-radius: 16px; padding: 24px; backdrop-filter: blur(12px); border: 1px solid rgba(255,255,255,0.18);} .glass-card--elevated { box-shadow: 0 8px 32px rgba(0,0,0,.35); }",
    },
  },
  {
    id: "neon-input",
    slug: "neon-input",
    name: "Neon Input",
    category: "forms",
    description: "Dark input field with neon focus ring and glowing border.",
    tags: ["input", "form", "neon"],
    difficulty: "beginner",
    author: "Showcase Team",
    demoAvailable: true,
    previewMetadata: { thumbnailKey: "neon-input" },
    useCase: "Use for dark-themed login and search forms.",
    accessibilityNotes: "Keep placeholder and helper text contrast at accessible levels.",
    responsiveNotes: "Input should expand to full width inside form stacks.",
    code: {
      jsx: "export default function NeonInput({ placeholder='Type...' }) { return <input className=\"neon-input\" placeholder={placeholder} />; }",
      css: ".neon-input { border-radius: 10px; border: 1px solid #334155; background: #0f172a; color: #e2e8f0; padding: 12px 16px; } .neon-input:focus { border-color: #fb923c; }",
    },
  },
  {
    id: "animated-navbar",
    slug: "animated-navbar",
    name: "Animated Navbar",
    category: "navigation",
    description: "Rounded navigation bar with animated underline interactions.",
    tags: ["navbar", "navigation", "animated"],
    difficulty: "intermediate",
    author: "Showcase Team",
    demoAvailable: true,
    previewMetadata: { thumbnailKey: "animated-navbar" },
    useCase: "Use in landing pages requiring animated top-level navigation.",
    accessibilityNotes: "Support keyboard navigation and visible active state.",
    responsiveNotes: "Allow wrapping links in narrow layouts.",
    code: {
      jsx: "export default function AnimatedNavbar() { return <nav className=\"animated-navbar\">{['Home','About','Projects','Contact'].map((x)=><a key={x} href=\"#\">{x}</a>)}</nav>; }",
      css: ".animated-navbar { display:flex; gap:24px; border-radius:999px; padding:14px 28px; } .animated-navbar a { position: relative; }",
    },
  },
  {
    id: "toast-notification",
    slug: "toast-notification",
    name: "Toast Notification",
    category: "feedback",
    description: "Status toast with success, error, and info visual variants.",
    tags: ["toast", "notification", "feedback"],
    difficulty: "beginner",
    author: "Showcase Team",
    demoAvailable: true,
    previewMetadata: { thumbnailKey: "toast-notification" },
    useCase: "Use to acknowledge saves, failures, and asynchronous actions.",
    accessibilityNotes: "Use aria-live polite for non-critical updates.",
    responsiveNotes: "Keep toast width constrained on small viewports.",
    code: {
      jsx: "export default function ToastNotification({ message='Saved', type='success' }) { return <div className={`toast-notification toast-notification-${type}`}><p>{message}</p></div>; }",
      css: ".toast-notification { padding: 14px 24px; border-radius: 10px; }",
    },
  },
  {
    id: "profile-card",
    slug: "profile-card",
    name: "Profile Card",
    category: "cards",
    description: "Team profile card with gradient avatar and skill chips.",
    tags: ["profile", "card", "team"],
    difficulty: "beginner",
    author: "Showcase Team",
    demoAvailable: true,
    previewMetadata: { thumbnailKey: "profile-card" },
    useCase: "Use for user cards, team bios, and contributor directories.",
    accessibilityNotes: "Provide accessible labels for avatar and actions.",
    responsiveNotes: "Card stacks in a responsive grid.",
    code: {
      jsx: "export default function ProfileCard() { return <article className=\"profile-card\"><h3>Team Member</h3><p>UI Component Engineer</p></article>; }",
      css: ".profile-card { border-radius: 18px; padding: 24px; border: 1px solid #334155; }",
    },
  },
  {
    id: "accessible-modal",
    slug: "modal",
    name: "Modal",
    category: "feedback",
    description: "Accessible modal dialog with controlled open state and Escape-key close.",
    tags: ["modal", "dialog", "accessibility"],
    difficulty: "intermediate",
    author: "Showcase Team",
    demoAvailable: true,
    previewMetadata: { thumbnailKey: "modal" },
    useCase: "Use for confirmation dialogs and critical workflow interruptions.",
    accessibilityNotes: "Trap focus in dialog and support Escape key closure.",
    responsiveNotes: "Center modal with max-width and viewport-safe padding.",
    code: {
      jsx: "export default function Modal({ open, onClose }) { return open ? <div role=\"dialog\"><button onClick={onClose}>Close</button></div> : null; }",
      css: ".modal-backdrop { position: fixed; inset: 0; display: grid; place-items: center; }",
    },
  },
  {
    id: "stateful-accordion",
    slug: "accordion",
    name: "Accordion",
    category: "navigation",
    description: "Expand and collapse sections with state-driven conditional rendering.",
    tags: ["accordion", "collapse", "state"],
    difficulty: "intermediate",
    author: "Showcase Team",
    demoAvailable: true,
    previewMetadata: { thumbnailKey: "accordion" },
    useCase: "Use for FAQs and dense settings pages.",
    accessibilityNotes: "Use aria-expanded and keyboard-triggerable buttons.",
    responsiveNotes: "Content wraps cleanly in narrow viewports.",
    code: {
      jsx: "export default function Accordion() { return <div className=\"accordion\">Accordion</div>; }",
      css: ".accordion { border: 1px solid #dbe2eb; border-radius: 12px; }",
    },
  },
  {
    id: "derived-state-tabs",
    slug: "tabs",
    name: "Tabs",
    category: "navigation",
    description: "Tabbed interface with active panel derived from selected tab state.",
    tags: ["tabs", "panel", "derived-state"],
    difficulty: "intermediate",
    author: "Showcase Team",
    demoAvailable: true,
    previewMetadata: { thumbnailKey: "tabs" },
    useCase: "Use to segment related content into compact panels.",
    accessibilityNotes: "Implement proper tablist, tab, and tabpanel roles.",
    responsiveNotes: "Allow tabs to wrap or scroll horizontally on mobile.",
    code: {
      jsx: "export default function Tabs() { return <div className=\"tabs\">Tabs</div>; }",
      css: ".tabs-list { display: flex; gap: 8px; }",
    },
  },
  {
    id: "data-table",
    slug: "data-table",
    name: "Data Table",
    category: "data",
    description: "Sortable table demo with threshold highlighting and optional row selection.",
    tags: ["table", "sorting", "data"],
    difficulty: "advanced",
    author: "Showcase Team",
    demoAvailable: true,
    previewMetadata: { thumbnailKey: "data-table" },
    useCase: "Use for admin dashboards and analytics rollups.",
    accessibilityNotes: "Ensure table semantics and sortable header controls are keyboard accessible.",
    responsiveNotes: "Allow horizontal scrolling inside constrained containers.",
    code: {
      jsx: "export default function DataTable() { return <table><tbody><tr><td>Data</td></tr></tbody></table>; }",
      css: "table { width: 100%; border-collapse: collapse; }",
    },
  },
  {
    id: "live-line-chart",
    slug: "live-line-chart",
    name: "Live Line Chart",
    category: "data",
    description: "SVG line chart with async data-feed simulation and threshold marker.",
    tags: ["chart", "line", "async"],
    difficulty: "advanced",
    author: "Showcase Team",
    demoAvailable: true,
    previewMetadata: { thumbnailKey: "line-chart" },
    useCase: "Use for real-time metrics and monitoring views.",
    accessibilityNotes: "Add descriptive labels and value summaries for non-visual users.",
    responsiveNotes: "Render using viewBox so chart scales fluidly.",
    code: {
      jsx: "export default function LiveLineChart() { return <svg viewBox=\"0 0 520 220\"><path d=\"M 0 0\" /></svg>; }",
      css: ".live-chart { width: 100%; border: 1px solid #dbe2eb; }",
    },
  },
];
